postgres_data:
  image: postgres
  volumes:
    - /var/lib/postgresql
  entrypoint: /bin/true
  container_name: hackdata
  
postgres_server:
  image: postgres
  environment:
    - POSTGRES_DB=hackmit
  volumes_from:
    - postgres_data
  container_name: hackdb

node:
  image: grid/node
  links:
    - postgres_server
  volumes:
    - /home/aria/Perspective/api/app:/usr/local/nodejs
  command: start api.js
  ports:
    - "3000:3000"
